name: flutter_image_editor_pro
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.6+1
  ml_linalg: ^13.11.28
  path_provider: ^2.0.12
  screenshot: ^2.1.0
  styled_widget: ^0.4.1
  unicons: ^2.1.0
  custom_image_crop:
    git:
      url: https://github.com/JosephKalash/flutter-custom-image-crop.git
      ref: 3a96b5b
  # path: ../flutter-custom-image-crop

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
